### ISSUE TITLE
Demo of the Capabilities

### ISSUE THREAD

**Issue by RoyiAvital** [steven2358/kafbox#3]
Hello,
Could you add for the front pages some graphs which shows the capabilities of the algorithms?

There is too little and it might bring much more interest once you show more plots.

Thank You.

**Comment by steven2358** [comment]
Good point. I will see if I can produce a graph that illustrates the general principle of online regression learning, which will serve for all algorithms here.

**Comment by RoyiAvital** [comment]
That would be great, I'd be happy to see it.

Thank You.
